apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "new.cluster.example"
spec:
  operations: ["CREATE"]
  resources: ["clusters"]
  javascript: |
    create({
      apiVersion: "v1",
      kind: "Pod",
      metadata: {
        name: "nginx-cl"
      },
      spec: {
        containers: [
          {
            name: "nginx-cl",
            image: "nginx:latest"
          }
        ]
      }
    });