apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "new-cluster-create"
spec:
  operations: ["CREATE"]
  resources: ["clusters"]
  javascript: |
    print("You create a new cluster");