apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "new.cluster.example"
spec:
  operations: ["CREATE", "DELETE"]
  resources: ["clusters"]
  javascript: |
   if request.object.status == create 
    create({
      apiVersion: "v1",
      kind: "Pod",
      metadata: {
        name: "nginx-cl",
        namespace: "fleet-local"
      },
      spec: {
        containers: [
          {
            name: "nginx-cl",
            image: "nginx:latest"
          }
        ]
      }
    });
   if request.object.status == delete
    remove(pod.nginx-cl)
