apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "new.cluster.example"
spec:
  operations: ["CREATE"]
  resources: ["clusters"]
  javascript: |
    const nameCl = request.object.metadata.name
    create({
      apiVersion: "v1",
      kind: "Pod",
      metadata: {
        name: nameCl,
        namespace: "fleet-local"
      },
      spec: {
        containers: [
          {      
            name: nameCl,
            image: "nginx:latest"
          }
        ]
      }
    });